name: Nuclio Model Deployment

on:
  push:

jobs:
  file-checking:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check_files.outputs.files_exists }}

    steps:
      - uses: actions/checkout@v2

      - name: Check file(s) existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "function.yaml, main.py, nuctl"
  
  nuctl-installation:
    needs: [file-checking]
    if: needs.file-checking.outputs.status == 'true'
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: create script
        run: echo 'curl -s https://api.github.com/repos/nuclio/nuclio/releases/latest | grep -i "browser_download_url.*nuctl.*$(uname)" | cut -d : -f 2,3 | tr -d \" | wget -O nuctl -qi - && chmod +x nuctl' > nuctl-script.sh

      - name: installation
        run: sh nuctl-script.sh 
      
  deployment:
    needs: [file-checking]
    if: needs.file-checking.outputs.status == 'true'
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: nuctl create project
        run: ./nuctl create project cvat
        
      - name: nuctl deploy
        run: ./nuctl deploy --project-name cvat --path . --platform local